/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavorilerRouteImport } from './routes/favoriler'
import { Route as KampRouteImport } from './routes/kamp'
import { Route as MuzelerRouteImport } from './routes/muzeler'
import { Route as RotalarRouteImport } from './routes/rotalar'
import { Route as TarihiRouteImport } from './routes/tarihi'
import { Route as UnescoRouteImport } from './routes/unesco'
import { Route as YuruyusRouteImport } from './routes/yuruyus'
import { Route as RotaIdRouteImport } from './routes/rota.$id'
import { Route as YerIdRouteImport } from './routes/yer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorilerRoute = FavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const KampRoute = KampRouteImport.update({
  id: '/kamp',
  path: '/kamp',
  getParentRoute: () => rootRouteImport,
} as any)
const MuzelerRoute = MuzelerRouteImport.update({
  id: '/muzeler',
  path: '/muzeler',
  getParentRoute: () => rootRouteImport,
} as any)
const RotalarRoute = RotalarRouteImport.update({
  id: '/rotalar',
  path: '/rotalar',
  getParentRoute: () => rootRouteImport,
} as any)
const TarihiRoute = TarihiRouteImport.update({
  id: '/tarihi',
  path: '/tarihi',
  getParentRoute: () => rootRouteImport,
} as any)
const UnescoRoute = UnescoRouteImport.update({
  id: '/unesco',
  path: '/unesco',
  getParentRoute: () => rootRouteImport,
} as any)
const YuruyusRoute = YuruyusRouteImport.update({
  id: '/yuruyus',
  path: '/yuruyus',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaIdRoute = RotaIdRouteImport.update({
  id: '/rota/$id',
  path: '/rota/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const YerIdRoute = YerIdRouteImport.update({
  id: '/yer/$id',
  path: '/yer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoriler': typeof FavorilerRoute
  '/kamp': typeof KampRoute
  '/muzeler': typeof MuzelerRoute
  '/rotalar': typeof RotalarRoute
  '/tarihi': typeof TarihiRoute
  '/unesco': typeof UnescoRoute
  '/yuruyus': typeof YuruyusRoute
  '/rota/$id': typeof RotaIdRoute
  '/yer/$id': typeof YerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoriler': typeof FavorilerRoute
  '/kamp': typeof KampRoute
  '/muzeler': typeof MuzelerRoute
  '/rotalar': typeof RotalarRoute
  '/tarihi': typeof TarihiRoute
  '/unesco': typeof UnescoRoute
  '/yuruyus': typeof YuruyusRoute
  '/rota/$id': typeof RotaIdRoute
  '/yer/$id': typeof YerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoriler': typeof FavorilerRoute
  '/kamp': typeof KampRoute
  '/muzeler': typeof MuzelerRoute
  '/rotalar': typeof RotalarRoute
  '/tarihi': typeof TarihiRoute
  '/unesco': typeof UnescoRoute
  '/yuruyus': typeof YuruyusRoute
  '/rota/$id': typeof RotaIdRoute
  '/yer/$id': typeof YerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favoriler'
    | '/kamp'
    | '/muzeler'
    | '/rotalar'
    | '/tarihi'
    | '/unesco'
    | '/yuruyus'
    | '/rota/$id'
    | '/yer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoriler'
    | '/kamp'
    | '/muzeler'
    | '/rotalar'
    | '/tarihi'
    | '/unesco'
    | '/yuruyus'
    | '/rota/$id'
    | '/yer/$id'
  id:
    | '__root__'
    | '/'
    | '/favoriler'
    | '/kamp'
    | '/muzeler'
    | '/rotalar'
    | '/tarihi'
    | '/unesco'
    | '/yuruyus'
    | '/rota/$id'
    | '/yer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavorilerRoute: typeof FavorilerRoute
  KampRoute: typeof KampRoute
  MuzelerRoute: typeof MuzelerRoute
  RotalarRoute: typeof RotalarRoute
  TarihiRoute: typeof TarihiRoute
  UnescoRoute: typeof UnescoRoute
  YuruyusRoute: typeof YuruyusRoute
  RotaIdRoute: typeof RotaIdRoute
  YerIdRoute: typeof YerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriler': {
      id: '/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof FavorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamp': {
      id: '/kamp'
      path: '/kamp'
      fullPath: '/kamp'
      preLoaderRoute: typeof KampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muzeler': {
      id: '/muzeler'
      path: '/muzeler'
      fullPath: '/muzeler'
      preLoaderRoute: typeof MuzelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotalar': {
      id: '/rotalar'
      path: '/rotalar'
      fullPath: '/rotalar'
      preLoaderRoute: typeof RotalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarihi': {
      id: '/tarihi'
      path: '/tarihi'
      fullPath: '/tarihi'
      preLoaderRoute: typeof TarihiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unesco': {
      id: '/unesco'
      path: '/unesco'
      fullPath: '/unesco'
      preLoaderRoute: typeof UnescoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yuruyus': {
      id: '/yuruyus'
      path: '/yuruyus'
      fullPath: '/yuruyus'
      preLoaderRoute: typeof YuruyusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota/$id': {
      id: '/rota/$id'
      path: '/rota/$id'
      fullPath: '/rota/$id'
      preLoaderRoute: typeof RotaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yer/$id': {
      id: '/yer/$id'
      path: '/yer/$id'
      fullPath: '/yer/$id'
      preLoaderRoute: typeof YerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavorilerRoute: FavorilerRoute,
  KampRoute: KampRoute,
  MuzelerRoute: MuzelerRoute,
  RotalarRoute: RotalarRoute,
  TarihiRoute: TarihiRoute,
  UnescoRoute: UnescoRoute,
  YuruyusRoute: YuruyusRoute,
  RotaIdRoute: RotaIdRoute,
  YerIdRoute: YerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
